name: Build and Push images to GCR

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read 

jobs:
  build:
    name: Build & Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Obtain access token by using workload identity federation
        uses: google-github-actions/auth@v2
        with:
            create_credentials_file: true
            token_format: access_token
            workload_identity_provider: projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-actions-vi-function-test/providers/github-actions-oidc-provider-id
            service_account:  github-actions@sunlit-hook-450703-s2.iam.gserviceaccount.com

      - name: Configure Docker for GCR
        run: |
          gcloud --quiet auth configure-docker ${{ secrets.REGISTRY }}

      - name: Build and push vifunction-store
        uses: docker/build-push-action@v3
        with:
          context: ./src/ViFunction.Store
          file: ./src/ViFunction.Store/Containerfile 
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/vi-function-test/vifunction-store:latest
      
      - name: Build and push vifunction-gateway
        uses: docker/build-push-action@v3
        with:
          context: ./src/ViFunction.Gateway
          file: ./src/ViFunction.Gateway/Containerfile 
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/vi-function-test/vifunction-gateway:latest
      
      - name: Build and push vifunction-imagebuilder
        uses: docker/build-push-action@v3
        with:
          context: ./src/ViFunction.ImageBuilder
          file: ./src/ViFunction.ImageBuilder/Containerfile 
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/vi-function-test/vifunction-imagebuilder:latest

      - name: Build and push vifunction-kubeops
        uses: docker/build-push-action@v3
        with:
          context: ./src/ViFunction.KubeOps
          file: ./src/ViFunction.KubeOps/Containerfile 
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/vi-function-test/vifunction-kubeops:latest
          
